### ISSUE TITLE
Jog Function

### ISSUE THREAD

**Issue by foxylad** [sir-buckyball/chrome-gcode-sender#43]
Thanks for a cool app. I'm using it to test my Elekslaser A3X.

The jog buttons don't do what I expect, but this may be a bug in my expectations. I expect it to move the step size in the given direction each time I click the control, but instead it only does it once - it goes to that location and stops.

Would it be more useful if it moved to the location and then reset it's  origin? This would make the jog buttons usable to set the home location before running a file.

**Comment by sir-buckyball** [comment]
I've seen the behavior you are describing. Specifically that the machine will jog once and then no more in that direction; almost as if it hit a soft limit or is stuck in absolute positioning mode instead of switching over to relative positioning mode. As far as I've been able to tell, it's not the fault of the application sending commands, but of the receiving device. Usually turning everything off then on again resolves it for me.
