### ISSUE TITLE
codes not being recognized

### ISSUE THREAD

**Issue by gaetgodi** [sir-buckyball/chrome-gcode-sender#55]
unimplemented gcode command: M117
unimplemented gcode command: M300

**Comment by sir-buckyball** [comment]
M series codes are machine specific.

If I had to guess, you are using Marlin firmware, where M117 corresponds to setting a message on an LCD panel, and M300 is for playing a tone. Neither of these codes affects the visualization of the code you are trying to send. If your machine responds normally, the presence should also not affect sending the file.

The warnings are intended to be rendered because it was as an unrecognized code, and without knowing your exact machine/firmware; it's safer to alert you to the issue.


Side note: Chrome is dropping support for chrome apps in a few months. I don't expect there will be any further updates to chrome-gcode-sender.

**Comment by gaetgodi** [comment]
Thank you, I am using an Ender 5 Pro, it is my first machine and I just got it. I like your gcode-sender, will it continue to work even if no longer supported?

**Comment by sir-buckyball** [comment]
https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html outlines the schedule when chrome apps will stop  working.

gcode-sender utilizes a special serial API, for which the alternative is not yet generally available.
